spring.application.name=dio-projeto-modulo5-curso4-spring-cloud-openfeign

spring.cloud.openfeign.client.config.sanction-client.url=http://192.168.64.1:3001
spring.cloud.openfeign.client.config.sanction-client.logger-level=full
spring.cloud.openfeign.client.config.sanction-client.default-request-headers.x-api-key=kyc-secret-123
spring.cloud.openfeign.circuitbreaker.enabled=true

logging.level.br.com.dio.dioprojetomodulo5curso4springcloudopenfeign.infrastructure.rest=DEBUG

